window.SITE_CONFIG={contactEmail:'YOUR-EMAIL@example.com'};

window.WATCHES=[
{id:'ga-2100bm-7a2',brand:'Casio G-SHOCK',name:'GA-2100BM-7A2',display:'GA-2100BM-7A2',type:'G-SHOCK 2100 Series',condition:'New / Mint',price:95,market:'£82–£110',image:'images/ga-2100bm-7a2.jpg',tag:'Casual icon',description:'A crisp white-and-black CasiOak design built around G-SHOCK toughness and the slim 2100 silhouette.',specs:[['Case','48.5 × 45.4 × 11.8 mm'],['Crystal','Mineral glass'],['Movement','Quartz'],['Water resistance','200 m / 20 bar'],['Functions','World time, stopwatch, timer, alarm, LED'] ]},
{id:'ga-b2100cd-1a4',brand:'Casio G-SHOCK',name:'GA-B2100CD-1A4',display:'GA-B2100CD-1A4',type:'Charles Darwin Foundation',condition:'New / Mint',price:145,market:'£125–£165',image:'images/ga-b2100cd-1a4.jpg',tag:'Collaboration',description:'A Charles Darwin Foundation collaboration inspired by the Galápagos marine iguana, combining vivid detailing with Tough Solar and Bluetooth.',specs:[['Case','48.5 × 45.4 × 11.9 mm'],['Movement','Tough Solar'],['Connectivity','Bluetooth / Smartphone Link'],['Water resistance','200 m / 20 bar'],['Crystal','Mineral glass'] ]},
{id:'gm-2100ymg-9a',brand:'Casio G-SHOCK',name:'GM-2100YMG-9A',display:'GM-2100YMG-9A',type:'G-STEEL / Fine Metallic',condition:'New / Mint',price:195,market:'£175–£260',image:'images/gm-2100ymg-9a.jpg',tag:'Metallic finish',description:'The gold-toned Fine Metallic 2100 pairs an octagonal steel bezel with a comfortable tough silicone band.',specs:[['Case','49.3 × 44.4 × 11.8 mm'],['Case material','Resin / stainless steel'],['Crystal','Mineral glass'],['Water resistance','200 m / 20 bar'],['Movement','Quartz'] ]},
{id:'spb001',brand:'Seiko',name:'Premier SPB001',display:'SPB001',type:'Premier',condition:'Mint',price:425,market:'£350–£500',image:'images/spb001.jpg',tag:'Classic',description:'A refined Seiko Premier dress piece with a timeless profile, intended for collectors who prefer understated elegance.',specs:[['Collection','Premier'],['Movement','Automatic / model dependent'],['Case','Stainless steel'],['Crystal','Confirm exact variant'],['Condition note','Please confirm box/papers and service history'] ]},
{id:'srpl57k1',brand:'Seiko',name:'5 Sports SRPL57K1',display:'SRPL57K1',type:'5 Sports SNXS',condition:'New / Mint',price:285,market:'£240–£340',image:'images/srpl57k1.jpg',tag:'Limited-feel styling',description:'A compact SNXS-inspired 5 Sports with a vintage-leaning presence, automatic 4R36 calibre and day/date display.',specs:[['Movement','4R36 automatic, hand-winding'],['Power reserve','Approx. 41 hours'],['Case','37.4 mm diameter / 12.5 mm thick'],['Crystal','Curved Hardlex'],['Water resistance','100 m / 10 bar'] ]},
{id:'ssc963p1',brand:'Seiko',name:'Prospex Speedtimer SSC963P1',display:'SSC963P1',type:'Prospex Speedtimer',condition:'New / Mint',price:525,market:'£480–£640',image:'images/ssc963p1.jpg',tag:'Chronograph',description:'A motorsport-inspired solar chronograph with a pale pink dial, sapphire crystal and a compact 39 mm case.',specs:[['Movement','V192 solar chronograph'],['Accuracy','±15 sec/month'],['Power reserve','Approx. 6 months'],['Case','39.0 mm / 13.3 mm'],['Crystal','Curved sapphire'],['Water resistance','100 m / 10 bar'] ]},
{id:'sbgr255',brand:'Grand Seiko',name:'SBGR255',display:'SBGR255',type:'Heritage Collection',condition:'Mint',price:2950,market:'£2,700–£3,900',image:'images/sbgr255.jpg',tag:'Grand Seiko',description:'A finely finished Grand Seiko Heritage automatic with Zaratsu-polished casework, sapphire crystal and an approximately 72-hour power reserve.',specs:[['Movement','9S65 automatic / hand-winding'],['Power reserve','Approx. 72 hours'],['Case','39.4 mm / 13.5 mm'],['Crystal','Dual-curved sapphire'],['Accuracy','Normal usage +10 to −1 sec/day'],['Water resistance','100 m / 10 bar'] ]},
{id:'srp770j1',brand:'Seiko',name:'Automatic SRP770J1',display:'SRP770J1',type:'Seiko Automatic',condition:'Mint',price:245,market:'£190–£300',image:'images/srp770j1.jpg',tag:'Everyday automatic',description:'A classic Seiko automatic with the versatility to dress up or down. Condition and exact accessories should be confirmed before sale.',specs:[['Movement','Automatic'],['Case','Stainless steel'],['Crystal','Mineral / variant dependent'],['Water resistance','Typical 100 m class'],['Condition note','Confirm exact dial/bracelet variant'] ]},
{id:'sne527p1',brand:'Seiko',name:'SNE527P1',display:'SNE527P1',type:'Solar Essentials',condition:'New / Mint',price:210,market:'£179–£260',image:'images/sne527p1.jpg',tag:'Sapphire + solar',description:'A practical 40 mm solar Seiko with sapphire crystal, black dial, day/date and approximately ten months of operation when fully charged.',specs:[['Movement','V158 solar'],['Accuracy','±15 sec/month'],['Power reserve','Approx. 10 months'],['Case','40.0 mm / 9.7 mm'],['Crystal','Sapphire'],['Water resistance','100 m / 10 bar'] ]},
{id:'sary097',brand:'Seiko',name:'Presage SARY097',display:'SARY097',type:'Presage',condition:'Mint',price:330,market:'£250–£420',image:'images/sary097.jpg',tag:'Presage',description:'A dress-oriented Presage with the collection’s signature emphasis on dial finishing and mechanical character.',specs:[['Collection','Presage'],['Movement','Automatic'],['Case','Stainless steel'],['Crystal','Confirm exact variant'],['Water resistance','Confirm exact variant'] ]},
{id:'snl041j1-snl044',brand:'Seiko',name:'Premier Kinetic Chronograph',display:'SNL041J1 / SNL044',type:'Premier Kinetic Chronograph',condition:'Mint',price:425,market:'£325–£550',image:'images/snl041j1-snl044.jpg',tag:'Kinetic chronograph',description:'A substantial Premier Kinetic Chronograph offering Seiko’s hybrid kinetic approach with a more formal, premium case design.',specs:[['Movement','Kinetic chronograph'],['Case','Stainless steel'],['Crystal','Variant dependent'],['Functions','Chronograph / date'],['Condition note','Confirm exact reference, bracelet and papers'] ]},
{id:'srbp99j1',brand:'Seiko',name:'Prospex PADI SRPB99J1',display:'SRPB99J1',type:'Prospex PADI',condition:'Mint',price:390,market:'£300–£450',image:'images/srpb99j1.jpg',tag:'PADI diver',description:'A Prospex PADI diver with the unmistakable blue-and-red PADI colour language and Seiko’s dive-watch heritage.',specs:[['Collection','Prospex PADI'],['Movement','Automatic'],['Crystal','Hardlex / variant dependent'],['Water resistance','Typically 200 m class'],['Functions','Time / date / dive bezel'] ]}
];